(library
 (name c_of_ocaml_lib)
 (libraries containers containers-data iter js_of_ocaml-compiler)
 (preprocess
  (pps ppx_deriving.show)))

(rule
 (with-stdout-to
  runtime_c_code.ml
  (progn
   (echo "let default = {plain_c_code|")
   (cat %{project_root}/runtime/runtime.c)
   (echo "|plain_c_code}\n\n")
   (echo "let avr = {plain_c_code|")
   (cat %{project_root}/runtime/runtime.atmega328p.c)
   (echo "|plain_c_code}"))))
